### PR TITLE
Add support for Interstitial Ads on Android

### PR DESCRIPTION
**Pull request by hansemannn**
Untested so far. Also no good parity with iOS, because of different events and not part of the "View" proxy. Android should get the iOS event naming and iOS should use `showInterstitial` instead. 

Alternatively, we should rather create a new proxy "Interstitial" that is used on both iOS and Android, so we would just need to deprecate the old iOS API.

### CODE REVIEW

**Comment by TomCatXY** [comment]
Hi hansemann!
is there a date, this version could be used in a production app? i'd need it in near future if possible.
br,
Christian

**Comment by egonbeermat** [comment]
Really would like this module to support interstitial on Android! :)

**Comment by hansemannn** [comment]
I can move forward as soon as you guys test the changes :-).

**Comment by TomCatXY** [comment]
How could I test it? sorry, i'm not keen to plugin-dev

**Comment by egonbeermat** [comment]
Concur with TomCatXY - can you at least provide a "release" package for testers? I spent a frustrating couple of hours trying to build the module; I don't dev modules/use the NDK, so it was a diversion trying to build something when I could have helped you more testing for 2 those hours :) Appreciate the work you are doing on this module, the community needs an up-to-date cross-platform adMob module

**Comment by bitfabrikken** [comment]
@hansemannn  I'm trying to test this, but I keep running into problems with regards to multidexing and google play services. I'm trying to test this module in a project that also has the Ti module google.analytics. Any tips?

**Comment by egonbeermat** [comment]
Caveat - I've never developed Titanium modules before, and never officially developed Java, but I can hack. After looking at your code for interstitials on Android (something I need badly!), I used it as a great starting point, hacked around and came up with the below AdmobModule.java, after finally getting my environment to build the module (SDK 6.1.0.GA and NDK r12b). Please feel free to clean this hack up (remove debugs, appropriate declarations and scoping, etc) and use, if you find it useful. 

My app will show interstitials occasionally throughout the usage of the app, so I feel it is best to have one "in hand", to minimize any wait times for the user. The below code (works for me) will instantiate the Interstitial and load the first one via createInterstitial, with an onAdLoaded event fired when the ad is loaded. The developer can then show this at any time via showInterstitial, and then request a new one be loaded, ready to show later, via refreshInterstitial (a good time to call the refresh is on the onAdClosed event, for instance, when the user dismisses the displayed interstitial).

I have tested this on my device, and it appears to work fine with test and real ads.
```java
/**
 * Copyright (c) 2011 by Studio Classics. All Rights Reserved.
 * Author: Brian Kurzius
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */

package ti.admob;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;
import com.google.android.gms.common.GooglePlayServicesUtil;
import com.google.android.gms.ads.AdListener;
import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.InterstitialAd;

@Kroll.module(name = "Admob", id = "ti.admob")
public class AdmobModule extends KrollModule {
	
	private static final String TAG = "AdmobModule";
	public static String MODULE_NAME = "AndroidAdMobModule";
	
    // constants
    @Kroll.constant public static final int AD_TYPE_BANNER = 0;
    @Kroll.constant public static final int AD_TYPE_INTERSTITIAL = 1;
    @Kroll.constant public static final String AD_RECEIVED = "ad_received";
    @Kroll.constant public static final String AD_NOT_RECEIVED = "ad_not_received";
    @Kroll.constant public static final String AD_OPENED = "ad_opened";
    @Kroll.constant public static final String AD_CLOSED = "ad_closed";
    @Kroll.constant public static final String AD_LEFT_APPLICATION = "ad_left_application";
    @Kroll.constant public static final int SUCCESS = 0;
    @Kroll.constant public static final int SERVICE_MISSING = 1;
    @Kroll.constant public static final int SERVICE_VERSION_UPDATE_REQUIRED = 2;
    @Kroll.constant public static final int SERVICE_DISABLED = 3;
    @Kroll.constant public static final int SERVICE_INVALID = 9;
    
    // properties
    public static String PROPERTY_AD_UNIT_ID = "adUnitId";
    public static String PROPERTY_AD_TYPE = "adType";
    public static String PROPERTY_DEBUG_ENABLED = "debugEnabled";
    public static String PROPERTY_TESTING = "testing";
    public static String PROPERTY_TEST_DEVICE = "testDevice";
    
    public static String PROPERTY_PUBLISHER_ID = "publisherId";
	public static String PROPERTY_COLOR_BG = "adBackgroundColor";
	public static String PROPERTY_COLOR_BG_TOP = "backgroundTopColor";
	public static String PROPERTY_COLOR_BORDER = "borderColor";
	public static String PROPERTY_COLOR_TEXT = "textColor";
	public static String PROPERTY_COLOR_LINK = "linkColor";
	public static String PROPERTY_COLOR_URL = "urlColor";
	public static String PROPERTY_COLOR_TEXT_DEPRECATED = "primaryTextColor";
	public static String PROPERTY_COLOR_LINK_DEPRECATED = "secondaryTextColor";
    
    public InterstitialAd interstitialAd;
    public AdRequest.Builder adRequestBuilder;
    
    public String prop_adUnitId;
    public Boolean prop_debugEnabled = false;
    public String prop_testDevice = AdRequest.DEVICE_ID_EMULATOR;

	public AdmobModule() {
		super();
		Log.d(TAG, "adMob module instantiated");
	}
    
    @Kroll.method
    public void createInterstitial(KrollDict args) {
        
        Log.d(TAG, "in createInterstitial");
        
        if (args.containsKey(AdmobModule.PROPERTY_AD_UNIT_ID)) {
            prop_adUnitId = args.getString(AdmobModule.PROPERTY_AD_UNIT_ID);
        }
        
        //Testing - defaults to emulator device_id if testDevice is not supplied
        if (args.containsKey(AdmobModule.PROPERTY_DEBUG_ENABLED)) {
            prop_debugEnabled = args.getBoolean(AdmobModule.PROPERTY_DEBUG_ENABLED);

            if (args.containsKey(AdmobModule.PROPERTY_TEST_DEVICE) && prop_debugEnabled) {
                prop_testDevice = args.getString(AdmobModule.PROPERTY_TEST_DEVICE);
            }
        }
        
        Log.d(TAG, "prop_testDevice: " + prop_testDevice);
        
        interstitialAd = new InterstitialAd(TiApplication.getInstance().getCurrentActivity());
        interstitialAd.setAdUnitId(prop_adUnitId);
        
        interstitialAd.setAdListener(new AdListener() {
            public void onAdLoaded() {
                Log.d(TAG, "onAdLoaded()");
                fireEvent(AdmobModule.AD_RECEIVED, new KrollDict());
            }
            
            public void onAdFailedToLoad(int errorCode) {
                Log.d(TAG, "onAdFailedToLoad(): " + errorCode);
                fireEvent(AdmobModule.AD_NOT_RECEIVED, new KrollDict());
            }
            
            public void onAdOpened() {
                Log.d(TAG, "onAdOpened()");
                fireEvent(AdmobModule.AD_OPENED, new KrollDict());
            }
            
            public void onAdClosed() {
                Log.d(TAG, "onAdClosed()");
                fireEvent(AdmobModule.AD_CLOSED, new KrollDict());
            }
            
            public void onAdLeftApplication() {
                Log.d(TAG, "onAdLeftApplication()");
                fireEvent(AdmobModule.AD_LEFT_APPLICATION, new KrollDict());
            }
        });
        
        //Get first interstitial
        refreshInterstitial();
    }
    
    @Kroll.method
    public void refreshInterstitial() {
        
        Log.d(TAG, "in refreshInterstitial");
        
        TiApplication.getInstance().getCurrentActivity().runOnUiThread(new Runnable() {
            public void run() {
                adRequestBuilder = new AdRequest.Builder();
                if (prop_debugEnabled) {
                    adRequestBuilder.addTestDevice(prop_testDevice);
                }
                interstitialAd.loadAd(adRequestBuilder.build());
            }
        });
    }
    
    @Kroll.method
    public void showInterstitial() {
        
        Log.d(TAG, "in showInterstitial");
        
        if (interstitialAd.isLoaded()) {
            interstitialAd.show();
        } else {
            Log.d("TAG", "The interstitial wasn't loaded yet.");
        }
    }
    
	@Kroll.method
	public int isGooglePlayServicesAvailable() {
		return GooglePlayServicesUtil.isGooglePlayServicesAvailable(TiApplication.getAppRootOrCurrentActivity());
	}
}

**Comment by hansemannn** [comment]
@egonbeermat It's time to get this in officially. I'll refactor some bits of the code and include it for the next release.

**Comment by KhoaNT2003** [comment]
@hansemannn Please release the version support Interstitia Ads soon. We have been waiting for this for a long time. This function is very important to many people.

**Comment by kerbooo** [comment]
Can we use this property now?

**Comment by SquirrelMobile** [comment]
@kerbooo you can use this module to support interstitial : https://github.com/JosephAustin/ti.admobint

**Comment by kerbooo** [comment]
@SquirrelMobile  Thank you very much for your support. So can we use that with SDK 7.0 and ti.playservice?

**Comment by hansemannn** [comment]
Closing in favor of the changes @fanhero is working on.

**Comment by kerbooo** [comment]
@hansemannn Thanks for your great module firstly. Please add this properties your module soon.

**Pull request closed without merging**
