### PR TITLE
Updating google ads ios sdk to 7.1.0 64bit support.

### PR DESCRIPTION
**Pull request by iampnelson**
Updating google ads ios sdk to 7.1.0 64bit support and removed old module 1.9.0 since it is no longer supported or will work with Titanium and 64bit.

### CODE REVIEW

**Comment by sfeather** [comment]
Paul,

First, thank you for the pull request. 
Couple of things.
1. Be sure to sign the CLA
2. Do not add ios/build/*
3. The ios/manifest needs to have the reference apiversion: 2
4. Is there a reason for the minsdk to be 3.5.0? (as opposed to lets say 3.4.x or 3.5.1)

**Comment by iampnelson** [comment]
Hi Stephen,

I chose 3.5.0 because that's the minimum for 64bit iOS.  I can change it to 3.5.1, no problem.  I will correct the other issues as well.  Thanks.

Cheers,
Paul

**Comment by nuno** [comment]
Hello @iampnelson thanks for the update, I tried use your build "2.0" and im afraid for me not works, this still works for you?  tisdk 4.1.1.GA  or 4.1.0.GA  appc studio beta.

Any info will be great. Thank you.

sample code
```
var Admob = require('ti.admob');
var self = Ti.UI.createWindow({
    backgroundColor : 'white'
});
//Ad placement
var viewBanner = Ti.UI.createView({
    bottom : 0,
    height : 50,
    width : 320,
    //borderColor: 'black',
    backgroundColor : '#afff',
    zIndex : 10
});
 
var AdMobID = 'ca-app-pub-6899365325952326/9239963693';
 
var tmrAds = setTimeout(function() {
    Ti.API.info('Requesting Ads...');
    
    banner = Admob.createView({
        bottom : 0,
        width : viewBanner.width,
        height : viewBanner.height,
        publisherId : AdMobID,
        //adBackgroundColor : 'blue',
       // testing : true,

    });
 
    //Set listeners
    banner.addEventListener('didReceiveAd', function(e) {
        Ti.API.info('New Ad');
        //banner.show();
    });
 
    banner.addEventListener('didFailToReceiveAd', function(e) {
        Ti.API.info('New ad failed');
        //banner.hide();
    });
 
   banner.show();
 
    //add now
    viewBanner.add(banner);
    self.add(viewBanner);
 
}, 4500);
 
self.open();
```

got console logs like:

```
[INFO] :   Invoking xcodebuild
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/testCode.build/Debug-iphonesimulator/testCode.build/Objects-normal/x86_64/testCode normal x86_64
[ERROR] :  (1 failure)
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/nuno/.appcelerator/install/4.1.3/package/node_modules/appc-cli-titanium/plugins/run.js:84:66)
    at ChildProcess.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:820:12)

```

**Comment by iRonin** [comment]
Any updates on this one?

**Comment by sfeather** [comment]
Couple of notes 

1. New admob has a min ios version of 8.0. so to use, you have to set the following in your tiapp.xml
```
<min-ios-ver>5.0</min-ios-ver>
```

2. The actual google binaries are missing, the framework folder only contains header files

3. I'd suggest moving the .framework into ios/platform, updating your xcode project to reference the new location.

4. Add a FRAMEWORK_SEARCH_PATHS to your module.xcconfig so the apps build process can find the frameworks to link to the binary (note the version must be correct)
```
FRAMEWORK_SEARCH_PATHS=$(SRCROOT)/../../modules/iphone/ti.admob/2.0.0/platform "~/Library/Application Support/Titanium/modules/iphone/ti.admob/2.0.0/platform"
```

5. Update OTHER_LDFLAGS inmodule.xcconfig to link the framework
```
-framework GoogleMobileAds
```

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator-modules/ti.admob/pull/42.

**Pull request closed without merging**
