### PR TITLE
[MOD-2196] Add iAd adapter, bump to 2.1.0

### PR DESCRIPTION
**Pull request by hansemannn**
JIRA: https://jira.appcelerator.org/browse/MOD-2196

### CODE REVIEW

**Comment by Astrovic** [comment]
Hi @hansemannn, 
i tested 2.1.0, but iAd adapter don't works, in the log i see this:

`[DEBUG] :  <Google> Cannot find an ad network adapter with the name(s): (
[DEBUG] :      GADMAdapterIAd
[DEBUG] :  ). Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.`

**Comment by hansemannn** [comment]
@Astrovic Updated the PR, forgot to link the `iAd.framework`, shame on me! Please try the updated packaged version, thank you! 
[ti.admob-iphone-2.1.0.zip](https://github.com/appcelerator-modules/ti.admob/files/121683/ti.admob-iphone-2.1.0.zip)

**Comment by Astrovic** [comment]
Good job @hansemannn !!! :)
The only thing I noticed is that, except for the first advertising, all subsequent advertising only show iAd advertising. I do not understand if it's a configuration problem on the AdMob control panel. But if I use the previous AdMob modules, this does not happen... happens only with 2.1.0 module. In any case, no error log appears :)

**Comment by AngelkPetkov** [comment]
CR and FT approved! Merging

**Pull request merged**
