### PR TITLE
added translucent theme to the AdActivity snippet in timodule.xml fixes #13

### LINKED ISSUE #13: Version 2.1.4 throws a message regarding translucent ads
Ads: Please set theme of AdActivity to @android:style/Theme.Translucent to enable transparent background interstitial ad.

### PR DESCRIPTION
**Pull request by stephenfeather**

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @stephenfeather, how exactly does this change effect existing users? Thanks!

**Comment by bitfabrikken** [comment]
@stephenfeather, when I compile, the theme bit is removed automatically by titanium, any ideas to prevent that?

**Comment by stephenfeather** [comment]
Lets be honest, after nearly 18 months, I really don't remember, don't care (and 18 months for the tickets to be addressed shows appc doesnt care either)

**Comment by hansemannn** [comment]
You did not provide any information regarding your PR and did not answer when I asked during review. Kindly, what do you expect me to do? And it doesn't seem to work either.

**Pull request closed without merging**
