### PR TITLE
[TIMODOPEN-467] Added Interstitial (fullscreen) ad support for iOS

### PR DESCRIPTION
**Pull request by bitfabrikken**
Hired a freelancer to implement interstial ads on iOS. This is the result.

### CODE REVIEW

**Comment by xavierlacot** [comment]
Big +1 for this feature :-)

**Comment by bitfabrikken** [comment]
Thank @xavierlacot :) Just hope it get's implemented in the main branch - I'm not too good with this stuff.

**Comment by ingo** [comment]
@bitfabrikken Thank you. Do you know if there is a JIRA ticket open for this already? I don't see one. If you would be so kinda as to create a feature request for it, I'll make sure it gets moved appropriately.

**Comment by bitfabrikken** [comment]
Thanks much @ingo, did not realize I had to submit anything on JIRA. Only have community, so submitted it here: https://jira.appcelerator.org/browse/TC-5205

**Comment by ingo** [comment]
Thanks, moved.

**Comment by ingo** [comment]
@sfeather Given your previous contributions, I'm happy to grant you merge access if you'd like to review/merge this item.

**Comment by hansemannn** [comment]
Hi @bitfabrikken, we just updated the ti.admob iOS module to 2.0.0 and rewrote the whole project based on the latest Admob iOS SDK 7.6.0. Can you update your PR to work with latest source as soon as it is merged? We'd still be happy to support this PR, thank you!

**Comment by bitfabrikken** [comment]
@hansemannn sorry, I had a freelancer make the interstitial support, and I don't know how to apply that code with the new 2.0.0 module. Hopefully someone else can do it :)

**Comment by hansemannn** [comment]
@bitfabrikken Actually got it working pretty quickly today, but the old solution you used added the view to the view hierarchy which produced some edge cases to make the content unresponsive after dismissing the modal ad. So I thought of `ad.load()` and `ad.show()` to make it more cleaner. 

Will need to resolve a memory bug and then make it part of the PR. Usage will be `adType: Admob.AD_TYPE_BANNER` and  `adType: Admob.AD_TYPE_INTERSTITIAL` to handle it more cleaner.

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator-modules/ti.admob/pull/42. Please check the new released version 2.0.0. Thanks!

**Pull request closed without merging**
