### PR TITLE
iOS8 : Upgrade AdMob iOS SDK to version 6.12.2, and iAd adapter added;

### PR DESCRIPTION
**Pull request by Astrovic**
Upgrade AdMob iOS SDK to version 6.12.2, and iAd adapter added;

### CODE REVIEW

**Comment by zumaxg** [comment]
Hi Astrovic,

Do you know a date to have this version published?

Thanks

**Comment by Astrovic** [comment]
I do not know, but you can do a build of my fork, it works perfectly. I'm already using it in different app in production.

**Comment by zumaxg** [comment]
I'll try it. Thanks a lot

**Comment by iRonin** [comment]
+1

**Comment by hansemannn** [comment]
Hi @Astrovic, thanks for the PR! We recently updated the Google Admob SDK to the latest 7.6.0 release.  Can you resolve your merge problems above so we can take a closer look? Also, I cannot see any usage of the iAd adapter, how is it handled?

**Comment by Astrovic** [comment]
Hi @hansemannn 
you simply need to add the library iAd (https://dl.google.com/dl/googleadmobadssdk/libadapteriad.zip) as shown here (https://github.com/Astrovic/ti.admob/blob/38ecf1cd90cd32c342518d2e4cf5c7ac2f071af1/ios/LibAdapterIAd-1.0.0/README.txt). You do not need anything else.. Directly from your AdMob account, you can enable the iAd mediation, between the various available mediations.

**Comment by hansemannn** [comment]
Sounds great! Is the library still up2date? Then we just need to resolve the merge problems are good to go.

**Comment by Astrovic** [comment]
This is the list of all libraries for mediation: https://developers.google.com/admob/android/mediation-networks
I think that I used was the only version, and should still work correctly.

But instead, the ti.admob Android version will be updated? Because since I updated to Ti SDK 5.1 it no longer works. When I add the banner to the window, win.add(adMobView); the application crashes :(

**Comment by hansemannn** [comment]
Thanks for opening the Android issue, the Android devs will take care of that. I also want to get the iAdAdapter in, can you please file a JIRA ticket to get the issue into planning? Shouldn't take too long after that.

**Comment by Astrovic** [comment]
Thanks to you.
I have not well understood your request. I had already opened a ticket last year (https://github.com/appcelerator-modules/ti.admob/issues/26), before having sent my pull request. What should I do?

**Comment by hansemannn** [comment]
No problem! A [JIRA ticket](https://jira.appcelerator.org) is a ticket that is part of our sprint planning. As soon as a ticket is created there, we can link PR's to the tickets and track it for our QE team.

**Comment by Astrovic** [comment]
Ah ok! This is my JIRA ticket: https://jira.appcelerator.org/browse/AC-593

**Comment by hansemannn** [comment]
@Astrovic: Just updated the module to support the iAd adapter and bumped the version to 2.1.0 (feature release), please test it here: 
[ti.admob-iphone-2.1.0.zip](https://github.com/appcelerator-modules/ti.admob/files/113619/ti.admob-iphone-2.1.0.zip)

**Comment by Astrovic** [comment]
Perfect @hansemannn thanks a lot! :) I will try it as soon as possible.

**Comment by Astrovic** [comment]
Hi @hansemannn, 
i tested 2.1.0, but iAd adapter don't works, in the log i see this:

`[DEBUG] :  <Google> Cannot find an ad network adapter with the name(s): (
[DEBUG] :      GADMAdapterIAd
[DEBUG] :  ). Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.`

**Pull request closed without merging**
